# Cleanup (OPTIONAL)

|Previous Notebook|Current Notebook|Next Notebook|
|:-:|:-:|:-:|
|[4.alignment.ipynb](./4.alignment.ipynb)|<i>5.cleanup.ipynb</i>|-|

This notebook clears up some last-minute dregs in the data. This notebook is _technically_ **OPTIONAL**. Depends on what kind of data you have.

In [1]:
import pandas as pd
import os

pd.set_option('display.max_colwidth', None)   # Show full cell contents
pd.set_option('display.max_columns', None)    # Show all columns
pd.set_option('display.width', None)          # Don't wrap lines
pd.set_option('display.float_format', '{:.0f}'.format)

## Cleaning up EEG Data

The EEG data was only recorded using `unix_ms` (technically it also has the Timestamp variable, but that's besides the point). In any case, we should at some point associate each `unix_ms` in the eeg data to a frame in our VR data. We can do this via a `merge_asof()`:

In [3]:
valid_participants = pd.read_csv('./data/valid_participant_offsets.csv')
for _, row in valid_participants.iterrows():

    # calcualte the participant directory
    pdir = f"./data/{row['p_id']}/trials/"
    print(pdir)
    
    # Get the offset for this participant
    offset = row['offset']

    # Get the simulation trials
    sims = pd.read_csv(os.path.join(pdir, 'simulations.csv')).drop(columns=['Unnamed: 0'])

    # Look at each trial
    for _, trial in sims.iterrows():
        trial_id = trial['trial_id']
        tdir = os.path.join(pdir, f"{trial_id}/simulation/")

        # Get the eeg processed and eeg_raw. Also get `eye.csv` to get a reference to both `unix_ms` and `frame` data.
        eeg_processed = pd.read_csv(tdir+'eeg_processed.csv').drop(columns=['Unnamed: 0'])
        eeg_raw = pd.read_csv(tdir+'eeg_raw.csv').drop(columns=['Unnamed: 0'])
        eye = pd.read_csv(tdir+'eye.csv')

        # Firstly, correct the timing
        eeg_processed['unix_ms_corrected'] = eeg_processed['unix_ms'] - offset
        eeg_raw['unix_ms_corrected'] = eeg_raw['unix_ms'] - offset

        # Secondly, make sure that both columns are integers (technically long)
        #eeg_processed['unix_ms_corrected'] = eeg_processed['unix_ms_corrected'].astype('int64')
        eeg_processed['unix_ms_corrected_int64'] = eeg_processed['unix_ms_corrected'].astype('int64')

        num_duplicates = eeg_processed.duplicated().sum()
        print(num_duplicates)

        eeg_processed_2 = eeg_processed.drop_duplicates()
        dt = eeg_processed_2['unix_ms'].diff()
        # Compute mean delta
        mean_dt_ms = dt.mean()
        # Convert to Hz (samples per second)
        sample_rate_hz = 1000 / mean_dt_ms
        print(f"Average sample rate: {sample_rate_hz:.2f} Hz")

        display(eeg_processed_2)
        

        """
        # Secondly, attach a `frame` column based on `eye`
        eeg_processed_corrected = pd.merge_asof(
            eeg_processed,
            eye[['unix_ms', 'frame']],
            left_on = 'unix_ms',
            right_on = 'unix_ms',
            direction = 'backward'
        )

        # Likely that some columns will be 

        display(eye, eeg_processed_corrected.tail(20))
        """

./data/P4_Muse2/trials/
5613
Average sample rate: 75.78 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1759611096,1759611096188,32,32231,1,0,0,0,0,-0,-0,0,0,0,0,0,1,1,0,0,1,1,-0,0,1759611096135,1759611096135
5,1759611096,1759611096189,32,32232,1,0,0,0,0,-0,-0,0,0,0,0,0,1,1,0,0,1,1,-0,0,1759611096136,1759611096136
10,1759611096,1759611096190,32,32233,1,0,0,0,0,-0,-0,0,0,0,0,0,1,1,0,0,1,1,-0,0,1759611096137,1759611096137
12,1759611096,1759611096211,32,32254,1,0,0,0,0,-0,-0,0,0,0,0,0,1,1,0,0,1,1,-0,0,1759611096158,1759611096158
13,1759611096,1759611096212,32,32255,1,0,0,0,0,-0,-0,0,0,0,0,0,1,1,0,0,1,1,-0,0,1759611096159,1759611096159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7945,1759611127,1759611127249,63,63292,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1759611127196,1759611127196
7946,1759611127,1759611127250,63,63293,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1759611127197,1759611127197
7951,1759611127,1759611127251,63,63294,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1759611127198,1759611127198
7956,1759611127,1759611127252,63,63295,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1759611127199,1759611127199
7962,1759611127,1759611127253,63,63296,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1759611127200,1759611127200

4611
Average sample rate: 74.95 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1759611127,1759611127297,63,63340,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1759611127244,1759611127244
4,1759611127,1759611127298,63,63341,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1759611127245,1759611127245
5,1759611127,1759611127299,63,63342,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1759611127246,1759611127246
11,1759611127,1759611127300,63,63343,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1759611127247,1759611127247
12,1759611127,1759611127341,63,63384,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1,1,-0,0,1759611127288,1759611127288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6499,1759611153,1759611152652,89,88695,-0,0,1,0,-0,0,0,0,0,1,1,0,1,1,0,0,1,1,-0,0,1759611152599,1759611152599
6503,1759611153,1759611152653,89,88696,-0,0,1,0,-0,0,0,0,0,1,1,0,1,1,0,0,1,1,-0,0,1759611152600,1759611152600
6504,1759611153,1759611152697,89,88740,-0,0,1,0,-0,0,0,0,0,1,1,0,1,1,0,0,1,1,-0,0,1759611152644,1759611152644
6509,1759611153,1759611152698,89,88741,-0,0,1,0,-0,0,0,0,0,1,1,0,1,1,0,0,1,1,-0,0,1759611152645,1759611152645
6515,1759611153,1759611152699,89,88742,-0,0,1,0,-0,0,0,0,0,1,1,0,1,1,0,0,1,1,-0,0,1759611152646,1759611152646

4811
Average sample rate: 79.08 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1759611153,1759611152741,89,88784,-0,0,1,0,-0,0,0,0,0,1,1,0,1,1,0,0,1,1,-0,0,1759611152688,1759611152688
3,1759611153,1759611152742,89,88785,-0,0,1,0,-0,0,0,0,0,1,1,0,1,1,0,0,1,1,-0,0,1759611152689,1759611152689
9,1759611153,1759611152743,89,88786,-0,0,1,0,-0,0,0,0,0,1,1,0,1,1,0,0,1,1,-0,0,1759611152690,1759611152690
12,1759611153,1759611152786,89,88829,-0,0,1,0,-0,0,0,0,0,1,1,0,1,1,0,0,1,1,-0,0,1759611152733,1759611152733
13,1759611153,1759611152787,89,88830,-0,0,1,0,-0,0,0,0,0,1,1,0,1,1,0,0,1,1,-0,0,1759611152734,1759611152734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6948,1759611180,1759611179900,116,115943,1,1,0,0,1,1,-0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1759611179847,1759611179847
6951,1759611180,1759611179901,116,115944,1,1,0,0,1,1,-0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1759611179848,1759611179848
6955,1759611180,1759611179901,116,115944,1,1,0,0,1,1,-0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1759611179848,1759611179848
6956,1759611180,1759611179902,116,115945,1,1,0,0,1,1,-0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1759611179849,1759611179849
6958,1759611180,1759611179903,116,115946,1,1,0,0,1,1,-0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1759611179850,1759611179850

4610
Average sample rate: 75.24 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1759611180,1759611179946,116,115989,1,1,0,0,1,1,-0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1759611179893,1759611179893
5,1759611180,1759611179947,116,115990,1,1,0,0,1,1,-0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1759611179894,1759611179894
10,1759611180,1759611179948,116,115991,1,1,0,0,1,1,-0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1759611179895,1759611179895
12,1759611180,1759611179991,116,116034,1,1,0,0,1,1,-0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1759611179938,1759611179938
15,1759611180,1759611179992,116,116035,1,1,0,0,1,1,-0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1759611179939,1759611179939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6516,1759611205,1759611205420,141,141463,1,1,0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1,1,-0,0,1759611205367,1759611205367
6520,1759611205,1759611205421,141,141464,1,1,0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1,1,-0,0,1759611205368,1759611205368
6521,1759611205,1759611205421,141,141464,1,1,0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1,1,-0,0,1759611205368,1759611205368
6522,1759611205,1759611205422,141,141465,1,1,0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1,1,-0,0,1759611205369,1759611205369
6527,1759611205,1759611205423,141,141466,1,1,0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1,1,-0,0,1759611205370,1759611205370

5835
Average sample rate: 75.92 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1759611205,1759611205444,141,141487,1,1,0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1,1,-0,0,1759611205391,1759611205391
2,1759611205,1759611205445,141,141488,1,1,0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1,1,-0,0,1759611205392,1759611205392
7,1759611205,1759611205446,141,141489,1,1,0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1,1,-0,0,1759611205393,1759611205393
12,1759611205,1759611205490,142,141533,1,1,0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1,1,-0,0,1759611205437,1759611205437
16,1759611205,1759611205491,142,141534,1,1,0,0,1,1,0,0,1,1,0,0,1,1,-0,0,1,1,-0,0,1759611205438,1759611205438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8280,1759611238,1759611237790,174,173833,0,1,1,0,0,1,0,0,1,1,0,0,1,1,-0,0,1,1,-1,0,1759611237737,1759611237737
8283,1759611238,1759611237791,174,173834,0,1,1,0,0,1,0,0,1,1,0,0,1,1,-0,0,1,1,-1,0,1759611237738,1759611237738
8287,1759611238,1759611237791,174,173834,0,1,1,0,0,1,0,0,1,1,0,0,1,1,-0,0,1,1,-1,0,1759611237738,1759611237738
8288,1759611238,1759611237792,174,173835,0,1,1,0,0,1,0,0,1,1,0,0,1,1,-0,0,1,1,-1,0,1759611237739,1759611237739
8290,1759611238,1759611237793,174,173836,0,1,1,0,0,1,0,0,1,1,0,0,1,1,-0,0,1,1,-1,0,1759611237740,1759611237740

2475
Average sample rate: 79.63 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1759611238,1759611237835,174,173878,0,1,1,0,0,1,0,0,1,1,0,0,1,1,-0,0,1,1,-1,0,1759611237782,1759611237782
2,1759611238,1759611237836,174,173879,0,1,1,0,0,1,0,0,1,1,0,0,1,1,-0,0,1,1,-1,0,1759611237783,1759611237783
7,1759611238,1759611237837,174,173880,0,1,1,0,0,1,0,0,1,1,0,0,1,1,-0,0,1,1,-1,0,1759611237784,1759611237784
12,1759611238,1759611237880,174,173923,0,1,1,0,0,1,0,0,1,1,0,0,1,1,-0,0,1,1,-1,0,1759611237827,1759611237827
16,1759611238,1759611237881,174,173924,0,1,1,0,0,1,0,0,1,1,0,0,1,1,-0,0,1,1,-1,0,1759611237828,1759611237828
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3576,1759611252,1759611251797,188,187840,0,1,1,0,0,1,1,0,1,1,1,0,1,1,0,0,1,1,-0,0,1759611251744,1759611251744
3579,1759611252,1759611251798,188,187841,0,1,1,0,0,1,1,0,1,1,1,0,1,1,0,0,1,1,-0,0,1759611251745,1759611251745
3583,1759611252,1759611251798,188,187841,0,1,1,0,0,1,1,0,1,1,1,0,1,1,0,0,1,1,-0,0,1759611251745,1759611251745
3584,1759611252,1759611251799,188,187842,0,1,1,0,0,1,1,0,1,1,1,0,1,1,0,0,1,1,-0,0,1759611251746,1759611251746
3585,1759611252,1759611251800,188,187843,0,1,1,0,0,1,1,0,1,1,1,0,1,1,0,0,1,1,-0,0,1759611251747,1759611251747

./data/P5/trials/
5433
Average sample rate: 129.23 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1760548209,1760548209404,62,61866,1,1,0,2,1,0,-0,-0,1,0,0,0,1,0,0,-1,1,0,-0,-1,1760548209448,1760548209447
1,1760548209,1760548209405,62,61867,1,1,0,2,1,0,-0,-0,1,0,0,0,1,0,0,-1,1,0,-0,-1,1760548209448,1760548209448
3,1760548209,1760548209406,62,61868,1,1,0,2,1,0,-0,-0,1,0,0,0,1,0,0,-1,1,0,-0,-1,1760548209450,1760548209449
4,1760548209,1760548209407,62,61869,1,1,0,2,1,0,-0,-0,1,0,0,0,1,0,0,-1,1,0,-0,-1,1760548209450,1760548209450
5,1760548209,1760548209408,62,61870,1,1,0,2,1,0,-0,-0,1,0,0,0,1,0,0,-1,1,0,-0,-1,1760548209452,1760548209451
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10946,1760548252,1760548252130,105,104592,0,0,0,2,-0,0,-0,-0,0,1,-0,0,1,1,-0,-1,1,0,-0,-1,1760548252174,1760548252173
10949,1760548252,1760548252131,105,104593,0,0,0,2,-0,0,-0,-0,0,1,-0,0,1,1,-0,-1,1,0,-0,-1,1760548252174,1760548252174
10951,1760548252,1760548252132,105,104594,0,0,0,2,-0,0,-0,-0,0,1,-0,0,1,1,-0,-1,1,0,-0,-1,1760548252176,1760548252175
10954,1760548252,1760548252133,105,104595,0,0,0,2,-0,0,-0,-0,0,1,-0,0,1,1,-0,-1,1,0,-0,-1,1760548252176,1760548252176
10955,1760548252,1760548252133,105,104595,0,0,-0,2,-0,0,-0,-0,0,1,-0,0,1,1,-0,-1,1,0,-0,-1,1760548252176,1760548252176

3455
Average sample rate: 141.70 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1760548252,1760548252178,105,104640,0,0,-0,2,-0,0,-0,-0,0,1,-0,0,1,1,-0,-1,1,0,-0,-1,1760548252222,1760548252221
2,1760548252,1760548252179,105,104641,0,0,-0,2,-0,0,-0,-0,0,1,-0,0,1,1,-0,-1,1,0,-0,-1,1760548252222,1760548252222
6,1760548252,1760548252180,105,104642,0,0,-0,2,-0,0,-0,-0,0,1,-0,0,1,1,-0,-1,1,0,-0,-1,1760548252224,1760548252223
10,1760548252,1760548252181,105,104643,0,0,-0,2,-0,0,-0,-0,0,1,-0,0,1,1,-0,-1,1,0,-0,-1,1760548252224,1760548252224
12,1760548252,1760548252265,105,104727,0,0,-0,2,-0,0,-0,-0,0,1,-0,0,1,1,-0,-1,1,0,-0,-1,1760548252308,1760548252308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7716,1760548282,1760548282323,135,134785,-0,0,0,2,-0,0,-0,-0,0,0,-0,0,1,1,-0,-1,1,1,-0,-1,1760548282366,1760548282366
7718,1760548282,1760548282324,135,134786,-0,0,0,2,-0,0,-0,-0,0,0,-0,0,1,1,-0,-1,1,1,-0,-1,1760548282368,1760548282367
7721,1760548282,1760548282325,135,134787,-0,0,0,2,-0,0,-0,-0,0,0,-0,0,1,1,-0,-1,1,1,-0,-1,1760548282368,1760548282368
7722,1760548282,1760548282326,135,134788,-0,0,0,2,-0,0,-0,-0,0,0,-0,0,1,1,-0,-1,1,1,-0,-1,1760548282370,1760548282369
7724,1760548282,1760548282327,135,134789,-0,0,0,2,-0,0,-0,-0,0,0,-0,0,1,1,-0,-1,1,1,-0,-1,1760548282370,1760548282370

3368
Average sample rate: 131.19 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1760548282,1760548282371,135,134833,-0,0,0,2,-0,0,-0,-0,0,0,-0,0,1,1,-0,-1,1,1,-0,-1,1760548282414,1760548282414
1,1760548282,1760548282372,135,134834,-0,0,0,2,-0,0,-0,-0,0,0,-0,0,1,1,-0,-1,1,1,-0,-1,1760548282416,1760548282415
4,1760548282,1760548282373,135,134835,-0,0,0,2,-0,0,-0,-0,0,0,-0,0,1,1,-0,-1,1,1,-0,-1,1760548282416,1760548282416
8,1760548282,1760548282374,135,134836,-0,0,0,2,-0,0,-0,-0,0,0,-0,0,1,1,-0,-1,1,1,-0,-1,1760548282418,1760548282417
12,1760548282,1760548282417,135,134879,-0,0,0,2,-0,0,-0,-0,0,0,-0,0,1,1,-0,-1,1,1,-0,-1,1760548282460,1760548282460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6888,1760548309,1760548309282,162,161744,-0,0,0,2,-0,0,-0,-0,0,0,0,0,1,1,-0,-1,1,1,-0,-1,1760548309326,1760548309325
6889,1760548309,1760548309283,162,161745,-0,0,0,2,-0,0,-0,-0,0,0,0,0,1,1,-0,-1,1,1,-0,-1,1760548309326,1760548309326
6891,1760548309,1760548309284,162,161746,-0,0,0,2,-0,0,-0,-0,0,0,0,0,1,1,-0,-1,1,1,-0,-1,1760548309328,1760548309327
6894,1760548309,1760548309285,162,161747,-0,0,0,2,-0,0,-0,-0,0,0,0,0,1,1,-0,-1,1,1,-0,-1,1760548309328,1760548309328
6897,1760548309,1760548309286,162,161748,-0,0,0,2,-0,0,-0,-0,0,0,0,0,1,1,-0,-1,1,1,-0,-1,1760548309330,1760548309329

3022
Average sample rate: 138.94 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1760548309,1760548309329,162,161791,-0,0,0,2,-0,0,-0,-0,0,0,0,0,1,1,-0,-1,1,1,-0,-1,1760548309372,1760548309372
1,1760548309,1760548309330,162,161792,-0,0,0,2,-0,0,-0,-0,0,0,0,0,1,1,-0,-1,1,1,-0,-1,1760548309374,1760548309373
3,1760548309,1760548309331,162,161793,-0,0,0,2,-0,0,-0,-0,0,0,0,0,1,1,-0,-1,1,1,-0,-1,1760548309374,1760548309374
5,1760548309,1760548309332,162,161794,-0,0,0,2,-0,0,-0,-0,0,0,0,0,1,1,-0,-1,1,1,-0,-1,1760548309376,1760548309375
7,1760548309,1760548309333,162,161795,-0,0,0,2,-0,0,-0,-0,0,0,0,0,1,1,-0,-1,1,1,-0,-1,1760548309376,1760548309376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6591,1760548335,1760548335070,188,187532,-0,-0,-0,2,-0,-0,-0,-0,0,1,0,0,1,1,-0,-1,1,0,-0,-1,1760548335114,1760548335113
6593,1760548335,1760548335071,188,187533,-0,-0,-0,2,-0,-0,-0,-0,0,1,0,0,1,1,-0,-1,1,0,-0,-1,1760548335114,1760548335114
6595,1760548335,1760548335072,188,187534,-0,-0,-0,2,-0,-0,-0,-0,0,1,0,0,1,1,-0,-1,1,0,-0,-1,1760548335116,1760548335115
6597,1760548335,1760548335073,188,187535,-0,-0,-0,2,-0,-0,-0,-0,0,1,0,0,1,1,-0,-1,1,0,-0,-1,1760548335116,1760548335116
6599,1760548335,1760548335074,188,187536,-0,-0,-0,2,-0,-0,-0,-0,0,1,0,0,1,1,-0,-1,1,0,-0,-1,1760548335118,1760548335117

3407
Average sample rate: 131.07 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1760548335,1760548335138,188,187600,-0,-0,-0,2,-0,-0,-0,-0,0,1,0,0,1,1,-0,-1,1,0,-0,-1,1760548335182,1760548335181
1,1760548335,1760548335139,188,187601,-0,-0,-0,2,-0,-0,-0,-0,0,1,0,0,1,1,-0,-1,1,0,-0,-1,1760548335182,1760548335182
2,1760548335,1760548335140,188,187602,-0,-0,-0,2,-0,-0,-0,-0,0,1,0,0,1,1,-0,-1,1,0,-0,-1,1760548335184,1760548335183
4,1760548335,1760548335141,188,187603,-0,-0,-0,2,-0,-0,-0,-0,0,1,0,0,1,1,-0,-1,1,0,-0,-1,1760548335184,1760548335184
6,1760548335,1760548335142,188,187604,-0,-0,-0,2,-0,-0,-0,-0,0,1,0,0,1,1,-0,-1,1,0,-0,-1,1760548335186,1760548335185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6972,1760548362,1760548362372,215,214834,-0,1,1,2,-0,1,1,-0,0,1,0,0,1,0,0,-1,1,0,-0,-1,1760548362416,1760548362415
6973,1760548362,1760548362373,215,214835,-0,1,1,2,-0,1,1,-0,0,1,0,0,1,0,0,-1,1,0,-0,-1,1760548362416,1760548362416
6974,1760548362,1760548362374,215,214836,-0,1,1,2,-0,1,1,-0,0,1,0,0,1,0,0,-1,1,0,-0,-1,1760548362418,1760548362417
6975,1760548362,1760548362375,215,214837,-0,1,1,2,-0,1,1,-0,0,1,0,0,1,0,0,-1,1,0,-0,-1,1760548362418,1760548362418
6977,1760548362,1760548362376,215,214838,-0,1,1,2,-0,1,1,-0,0,1,0,0,1,0,0,-1,1,0,-0,-1,1760548362420,1760548362419

2496
Average sample rate: 130.85 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1760548362,1760548362376,215,214838,-0,1,1,2,-0,1,1,-0,0,1,0,0,1,0,0,-1,1,0,-0,-1,1760548362420,1760548362419
1,1760548362,1760548362377,215,214839,-0,1,1,2,-0,1,1,-0,0,1,0,0,1,0,0,-1,1,0,-0,-1,1760548362420,1760548362420
4,1760548362,1760548362378,215,214840,-0,1,1,2,-0,1,1,-0,0,1,0,0,1,0,0,-1,1,0,-0,-1,1760548362422,1760548362421
5,1760548362,1760548362380,215,214842,-0,1,1,2,-0,1,1,-0,0,1,0,0,1,0,0,-1,1,0,-0,-1,1760548362424,1760548362423
6,1760548362,1760548362381,215,214843,-0,1,1,2,-0,1,1,-0,0,1,0,0,1,0,0,-1,1,0,-0,-1,1760548362424,1760548362424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5125,1760548383,1760548382501,235,234963,1,0,1,2,0,-0,0,-0,0,1,-0,0,1,0,0,-1,1,1,0,-1,1760548382544,1760548382544
5126,1760548383,1760548382502,235,234964,1,0,1,2,0,-0,0,-0,0,1,-0,0,1,0,0,-1,1,1,0,-1,1760548382546,1760548382545
5127,1760548383,1760548382504,235,234966,1,0,1,2,0,-0,0,-0,0,1,-0,0,1,0,0,-1,1,1,0,-1,1760548382548,1760548382547
5128,1760548383,1760548382505,235,234967,1,0,1,2,0,-0,0,-0,0,1,-0,0,1,0,0,-1,1,1,0,-1,1760548382548,1760548382548
5129,1760548383,1760548382506,235,234968,1,0,1,2,0,-0,0,-0,0,1,-0,0,1,0,0,-1,1,1,0,-1,1760548382550,1760548382549

./data/PI2/trials/
4269
Average sample rate: 76.16 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1758754706,1758754705941,47,46860,1,-0,0,1,2,-0,1,1,2,0,1,1,2,0,1,0,1,-0,1,-0,1758754705841,1758754705841
4,1758754706,1758754705942,47,46861,1,-0,0,1,2,-0,1,1,2,0,1,1,2,0,1,0,1,-0,1,-0,1758754705842,1758754705842
11,1758754706,1758754705943,47,46862,1,-0,0,1,2,-0,1,1,2,0,1,1,2,0,1,0,1,-0,1,-0,1758754705843,1758754705843
12,1758754706,1758754705964,47,46883,1,-0,0,1,2,-0,1,1,2,0,1,1,2,0,1,0,1,-0,1,-0,1758754705864,1758754705864
15,1758754706,1758754705964,47,46883,1,-0,0,1,2,-0,1,1,2,0,1,1,2,0,1,0,1,-0,1,-0,1758754705864,1758754705864
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6048,1758754730,1758754729556,70,70475,1,-0,-0,0,2,1,0,0,1,0,1,-0,2,0,1,0,1,-0,1,-0,1758754729456,1758754729456
6052,1758754730,1758754729557,70,70476,1,-0,-0,0,2,1,0,0,1,0,1,-0,2,0,1,0,1,-0,1,-0,1758754729457,1758754729457
6060,1758754730,1758754729600,71,70519,1,-0,-0,0,2,1,0,0,1,0,1,-0,2,0,1,0,1,-0,1,-0,1758754729500,1758754729500
6062,1758754730,1758754729601,71,70520,1,-0,-0,0,2,1,0,0,1,0,1,-0,2,0,1,0,1,-0,1,-0,1758754729501,1758754729501
6070,1758754730,1758754729602,71,70521,1,-0,-0,0,2,1,0,0,1,0,1,-0,2,0,1,0,1,-0,1,-0,1758754729502,1758754729502

4731
Average sample rate: 66.79 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1758754730,1758754729664,71,70583,1,-0,-0,0,2,1,0,0,1,0,1,-0,2,0,1,0,1,-0,1,-0,1758754729564,1758754729564
1,1758754730,1758754729664,71,70583,1,0,-0,0,2,0,0,0,2,0,1,-0,2,0,1,0,1,-0,1,-0,1758754729564,1758754729564
2,1758754730,1758754729665,71,70584,1,0,-0,0,2,0,0,0,2,0,1,-0,2,0,1,0,1,-0,1,-0,1758754729565,1758754729565
8,1758754730,1758754729666,71,70585,1,0,-0,0,2,0,0,0,2,0,1,-0,2,0,1,0,1,-0,1,-0,1758754729566,1758754729566
12,1758754730,1758754729751,71,70670,1,0,-0,0,2,0,0,0,2,0,1,-0,2,0,1,0,1,-0,1,-0,1758754729651,1758754729651
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6371,1758754754,1758754754490,95,95409,1,1,0,0,2,0,0,-0,2,0,0,1,2,0,1,0,1,-0,1,-0,1758754754390,1758754754390
6372,1758754755,1758754754534,95,95453,1,1,0,0,2,0,0,-0,2,0,0,1,2,0,1,0,1,-0,1,-0,1758754754434,1758754754434
6379,1758754755,1758754754535,95,95454,1,1,0,0,2,0,0,-0,2,0,0,1,2,0,1,0,1,-0,1,-0,1758754754435,1758754754435
6384,1758754755,1758754754577,95,95496,1,1,0,0,2,0,0,-0,2,0,0,1,2,0,1,0,1,-0,1,-0,1758754754477,1758754754477
6390,1758754755,1758754754578,95,95497,1,1,0,0,2,0,0,-0,2,0,0,1,2,0,1,0,1,-0,1,-0,1758754754478,1758754754478

4985
Average sample rate: 64.82 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1758754755,1758754754621,96,95540,1,1,0,0,2,0,0,-0,2,0,0,1,2,0,1,0,1,-0,1,-0,1758754754521,1758754754521
1,1758754755,1758754754621,96,95540,1,1,0,0,2,1,0,-0,2,0,0,1,2,0,1,0,1,-0,1,-0,1758754754521,1758754754521
4,1758754755,1758754754622,96,95541,1,1,0,0,2,1,0,-0,2,0,0,1,2,0,1,0,1,-0,1,-0,1758754754522,1758754754522
12,1758754755,1758754754686,96,95605,1,1,0,0,2,1,0,-0,2,0,0,1,2,0,1,0,1,-0,1,-0,1758754754586,1758754754586
23,1758754755,1758754754687,96,95606,1,1,0,0,2,1,0,-0,2,0,0,1,2,0,1,0,1,-0,1,-0,1758754754587,1758754754587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6653,1758754781,1758754780589,122,121508,1,1,-0,0,2,0,-0,0,2,1,0,0,2,0,1,0,1,0,1,0,1758754780489,1758754780489
6657,1758754781,1758754780589,122,121508,1,0,-0,0,2,0,-0,0,2,0,0,0,2,0,1,0,1,0,1,0,1758754780489,1758754780489
6658,1758754781,1758754780590,122,121509,1,0,-0,0,2,0,-0,0,2,0,0,0,2,0,1,0,1,0,1,0,1758754780490,1758754780490
6660,1758754781,1758754780632,122,121551,1,0,-0,0,2,0,-0,0,2,0,0,0,2,0,1,0,1,0,1,0,1758754780532,1758754780532
6665,1758754781,1758754780633,122,121552,1,0,-0,0,2,0,-0,0,2,0,0,0,2,0,1,0,1,0,1,0,1758754780533,1758754780533

4380
Average sample rate: 64.92 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1758754781,1758754780677,122,121596,1,0,-0,0,2,0,-0,0,2,0,0,0,2,0,1,0,1,0,1,0,1758754780577,1758754780577
6,1758754781,1758754780678,122,121597,1,0,-0,0,2,0,-0,0,2,0,0,0,2,0,1,0,1,0,1,0,1758754780578,1758754780578
11,1758754781,1758754780678,122,121597,1,0,-0,0,2,0,-0,0,2,0,0,0,2,0,1,0,1,0,1,0,1758754780578,1758754780578
12,1758754781,1758754780721,122,121640,1,0,-0,0,2,0,-0,0,2,0,0,0,2,0,1,0,1,0,1,0,1758754780621,1758754780621
14,1758754781,1758754780722,122,121641,1,0,-0,0,2,0,-0,0,2,0,0,0,2,0,1,0,1,0,1,0,1758754780622,1758754780622
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5844,1758754804,1758754803515,144,144434,1,1,-0,1,2,1,1,0,2,1,1,1,2,1,1,0,1,0,1,-0,1758754803415,1758754803415
5854,1758754804,1758754803516,144,144435,1,1,-0,1,2,1,1,0,2,1,1,1,2,1,1,0,1,0,1,-0,1758754803416,1758754803416
5856,1758754804,1758754803580,144,144499,1,1,-0,1,2,1,1,0,2,1,1,1,2,1,1,0,1,0,1,-0,1758754803480,1758754803480
5861,1758754804,1758754803580,144,144499,1,1,-0,1,2,1,1,0,2,1,1,1,2,1,1,0,1,0,1,-0,1758754803480,1758754803480
5862,1758754804,1758754803581,144,144500,1,1,-0,1,2,1,1,0,2,1,1,1,2,1,1,0,1,0,1,-0,1758754803481,1758754803481

4923
Average sample rate: 64.79 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1758754804,1758754803623,145,144542,1,1,-0,1,2,1,1,0,2,1,1,1,2,1,1,0,1,0,1,-0,1758754803523,1758754803523
1,1758754804,1758754803624,145,144543,1,1,-0,1,2,1,1,0,2,1,1,1,2,1,1,0,1,0,1,-0,1758754803524,1758754803524
9,1758754804,1758754803625,145,144544,1,1,-0,1,2,1,1,0,2,1,1,1,2,1,1,0,1,0,1,-0,1758754803525,1758754803525
12,1758754804,1758754803710,145,144629,1,1,-0,1,2,1,1,0,2,1,1,1,2,1,1,0,1,0,1,-0,1758754803610,1758754803610
16,1758754804,1758754803711,145,144630,1,1,-0,1,2,1,1,0,2,1,1,1,2,1,1,0,1,0,1,-0,1758754803611,1758754803611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6567,1758754829,1758754829260,170,170179,1,1,0,0,2,0,0,-0,2,-0,1,0,2,1,1,0,1,0,1,-0,1758754829160,1758754829160
6571,1758754829,1758754829260,170,170179,1,1,0,0,2,-0,0,-0,2,0,1,0,2,0,1,0,1,0,1,-0,1758754829160,1758754829160
6572,1758754829,1758754829261,170,170180,1,1,0,0,2,-0,0,-0,2,0,1,0,2,0,1,0,1,0,1,-0,1758754829161,1758754829161
6576,1758754829,1758754829303,170,170222,1,1,0,0,2,-0,0,-0,2,0,1,0,2,0,1,0,1,0,1,-0,1758754829203,1758754829203
6584,1758754829,1758754829304,170,170223,1,1,0,0,2,-0,0,-0,2,0,1,0,2,0,1,0,1,0,1,-0,1758754829204,1758754829204

2459
Average sample rate: 66.08 Hz

,unix_sec,unix_ms,rel_sec,rel_ms,Delta_TP9,Delta_TP10,Delta_AF7,Delta_AF8,Theta_TP9,Theta_TP10,Theta_AF7,Theta_AF8,Alpha_TP9,Alpha_TP10,Alpha_AF7,Alpha_AF8,Beta_TP9,Beta_TP10,Beta_AF7,Beta_AF8,Gamma_TP9,Gamma_TP10,Gamma_AF7,Gamma_AF8,unix_ms_corrected,unix_ms_corrected_int64
0,1758754829,1758754829347,170,170266,1,1,0,0,2,-0,0,-0,2,0,1,0,2,0,1,0,1,0,1,-0,1758754829247,1758754829247
6,1758754829,1758754829348,170,170267,1,1,0,0,2,-0,0,-0,2,0,1,0,2,0,1,0,1,0,1,-0,1758754829248,1758754829248
9,1758754829,1758754829348,170,170267,1,1,0,0,2,-0,0,-0,2,0,0,0,2,0,1,0,1,0,1,-0,1758754829248,1758754829248
11,1758754829,1758754829349,170,170268,1,1,0,0,2,-0,0,-0,2,0,0,0,2,0,1,0,1,0,1,-0,1758754829249,1758754829249
12,1758754829,1758754829390,170,170309,1,1,0,0,2,-0,0,-0,2,0,0,0,2,0,1,0,1,0,1,-0,1758754829290,1758754829290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3288,1758754842,1758754842195,183,183114,2,2,0,1,2,2,0,-0,2,1,0,-0,1,1,1,0,1,0,1,-0,1758754842095,1758754842095
3294,1758754842,1758754842196,183,183115,2,2,0,1,2,2,0,-0,2,1,0,-0,1,1,1,0,1,0,1,-0,1758754842096,1758754842096
3300,1758754842,1758754842239,183,183158,2,2,0,1,2,2,0,-0,2,1,0,-0,1,1,1,0,1,0,1,-0,1758754842139,1758754842139
3306,1758754842,1758754842240,183,183159,2,2,0,1,2,2,0,-0,2,1,0,-0,1,1,1,0,1,0,1,-0,1758754842140,1758754842140
3311,1758754842,1758754842240,183,183159,2,2,0,1,2,2,0,-0,2,1,0,-0,1,1,1,0,1,0,1,-0,1758754842140,1758754842140